CREATE TABLE `#__md_new_member` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `tower_id` int(3) DEFAULT NULL,
  `forenames` varchar(50) DEFAULT NULL,
  `surname` varchar(50) DEFAULT NULL,
  `title` varchar(12) DEFAULT NULL,
  `member_type_id` int(11) NOT NULL,
  `long_service` varchar(8) NOT NULL DEFAULT 'No',
  `insurance_group` varchar(10) DEFAULT NULL,
  `annual_report` tinyint(1) DEFAULT NULL,
  `telephone` varchar(28) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `newsletters` varchar(7) DEFAULT NULL,
  `district_newsletters` int(11) NOT NULL DEFAULT '0',
  `date_elected` varchar(21) DEFAULT NULL,
  `address1` varchar(100) DEFAULT NULL,
  `address2` varchar(100) DEFAULT NULL,
  `address3` varchar(100) DEFAULT NULL,
  `town` varchar(50) DEFAULT NULL,
  `county` varchar(20) DEFAULT NULL,
  `postcode` varchar(9) DEFAULT NULL,
  `country` varchar(2) DEFAULT NULL,
  `dbs_date` varchar(10) DEFAULT NULL,
  `dbs_update` varchar(10) DEFAULT NULL,
  `mod_date` timestamp NULL DEFAULT NULL,
  `accept_privicy_policy` tinyint(1) NOT NULL DEFAULT '0',
  `soudbow_subscriber` tinyint(1) NOT NULL DEFAULT '0',
  `can_publish_name` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

